### ISSUE TITLE
Can not build the project in W11 on ARM64

### ISSUE THREAD

**Issue by alexwan7** [skvark/opencv-python#1092]
I failed to install the package directly from PIP or manual build.
I found a related issue opened at https://github.com/opencv/opencv-python/pull/644#issuecomment-1091903761 from two years ago. I installed all the tools and dependencies mentioned in the comment and repository's  Manual Build section. However, I see bunch of error messages related to the cmake building.

I am wondering if ARM64 on W11 is supported? Could you please add the ARM64 on windows wheel to the CI?

**Comment by khmyznikov** [comment]
Please provide [native wheel for WoA](https://blogs.windows.com/windowsdeveloper/2025/04/14/github-actions-now-supports-windows-on-arm-runners-for-all-public-repos/). GitHub Actions now supports win-arm64 for free.

Due to the library's popularity, a native version for the growing number of Windows on ARM (WoA) devices offers a better user experience

**Comment by khmyznikov** [comment]
Latest info about the build process I have:

- VS22 with v143 toolkits. No success.
- VS19 with v142 toolkits. No success. Issue with virtual memory. Couldn't make it work.
- Got back to VS22 to debug those errors. Issues are related to FP16 support or better to say non-support. MSVC++ doesn't support FP16 identifiers used all across opencv-python codebase. Tried replacing them with known data types, but it would take some time considering how deep some of them are inside modules.
- Had to turn off NEON flag. Take a look at the snippet
- After carefully examining all problematic paths, turned out they are related to only two files - Winograd convolution and standard convolution. Both part of so-called DNN module.
- I simply turned DNN modules build off and build it without them.

```python
cmake_args.append("-DBUILD_opencv_dnn=OFF")
cmake_args.append("-DENABLE_NEON=OFF")
```

**Comment by khmyznikov** [comment]
related https://github.com/opencv/opencv-python/issues/806

**Comment by Avasam** [comment]
> * I simply turned DNN modules build off and build it without them.
> 
> cmake_args.append("-DBUILD_opencv_dnn=OFF")
> cmake_args.append("-DENABLE_NEON=OFF")

Thanks!

So in GitHub action, this is how I achieved it:
```yaml
env:
  # https://github.com/opencv/opencv-python#source-distributions
  # Allows building OpenCV on Windows ARM64
  # https://github.com/opencv/opencv-python/issues/1092#issuecomment-2862538656
  CMAKE_ARGS: "-DBUILD_opencv_dnn=OFF -DENABLE_NEON=OFF"

jobs:
  Build:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install opencv-contrib-python-headless
```
